In [1]:
import pandas as pd 
import numpy as np

In [3]:
df=pd.DataFrame({ 'product':['carrots','braccoli','banna','banna',
                            'beans','orange','braccoli','banna'],
                 'categary':['vegetable','vegetavle','fruit','fruit','vegetable','vegetavle','fruit','fruit'],
                 'quantity':[8,5,3,4,5,9,11,8],
                 'amount':[270,239,617,384,626,610,62,90]
    
})

In [4]:
df

    product   categary  quantity  amount
0   carrots  vegetable         8     270
1  braccoli  vegetavle         5     239
2     banna      fruit         3     617
3     banna      fruit         4     384
4     beans  vegetable         5     626
5    orange  vegetavle         9     610
6  braccoli      fruit        11      62
7     banna      fruit         8      90

In [6]:
result=pd.pivot_table(df,index=['product','categary'],values=["amount"],aggfunc=[np.sum])

In [8]:
result

                      sum
                   amount
product  categary
banna    fruit       1091
beans    vegetable    626
braccoli fruit         62
         vegetavle    239
carrots  vegetable    270
orange   vegetavle    610

In [9]:
result=pd.pivot_table(df,index=['product'],values=['amount'],aggfunc=[np.min,np.median,np.mean])

In [10]:
result

            min median        mean
         amount amount      amount
product
banna        90  384.0  363.666667
beans       626  626.0  626.000000
braccoli     62  150.5  150.500000
carrots     270  270.0  270.000000
orange      610  610.0  610.000000

In [11]:


df = pd.read_csv("SaleData.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 15: invalid start byte