In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('sampledata.csv')

In [3]:
df=pd.DataFrame(data)
df

     price  year  km_driven
0   45,000  2026  45,000 km
1  231,100  2024  22,000 km
2   40,000  year  21,000 km
3   21,000    na  12,000 km
4   15,000  2025  23,000 km
5   18,000  2021  24,000 km
6      NaN  2022  32,000 km
7    price  2021  21,000 km
8   89,000  2023   2000p km

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   price      8 non-null      str
 1   year       9 non-null      str
 2   km_driven  9 non-null      str
dtypes: str(3)
memory usage: 348.0 bytes

In [5]:
data['price'].str.isnumeric()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: price, dtype: bool

In [6]:
df['price'].astype(str)

0     45,000
1    231,100
2     40,000
3     21,000
4     15,000
5     18,000
6        NaN
7      price
8     89,000
Name: price, dtype: str

In [7]:
df['price']=df['price'].str.replace(',','')

In [8]:
df

    price  year  km_driven
0   45000  2026  45,000 km
1  231100  2024  22,000 km
2   40000  year  21,000 km
3   21000    na  12,000 km
4   15000  2025  23,000 km
5   18000  2021  24,000 km
6     NaN  2022  32,000 km
7   price  2021  21,000 km
8   89000  2023   2000p km

In [9]:
df=df[df['price'].str.isnumeric()]

In [10]:
df

    price  year  km_driven
0   45000  2026  45,000 km
1  231100  2024  22,000 km
2   40000  year  21,000 km
3   21000    na  12,000 km
4   15000  2025  23,000 km
5   18000  2021  24,000 km
8   89000  2023   2000p km

In [11]:
df.shape

(7, 3)

In [12]:
df

    price  year  km_driven
0   45000  2026  45,000 km
1  231100  2024  22,000 km
2   40000  year  21,000 km
3   21000    na  12,000 km
4   15000  2025  23,000 km
5   18000  2021  24,000 km
8   89000  2023   2000p km

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 7 entries, 0 to 8
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   price      7 non-null      str
 1   year       7 non-null      str
 2   km_driven  7 non-null      str
dtypes: str(3)
memory usage: 224.0 bytes

In [14]:
df

    price  year  km_driven
0   45000  2026  45,000 km
1  231100  2024  22,000 km
2   40000  year  21,000 km
3   21000    na  12,000 km
4   15000  2025  23,000 km
5   18000  2021  24,000 km
8   89000  2023   2000p km

In [15]:
df['price'].astype(str)

0     45000
1    231100
2     40000
3     21000
4     15000
5     18000
8     89000
Name: price, dtype: str

In [16]:
data=pd.read_csv('sampledata.csv')

In [17]:
df=pd.DataFrame(data)
df

     price  year  km_driven
0   45,000  2026  45,000 km
1  231,100  2024  22,000 km
2   40,000  year  21,000 km
3   21,000    na  12,000 km
4   15,000  2025  23,000 km
5   18,000  2021  24,000 km
6      NaN  2022  32,000 km
7    price  2021  21,000 km
8   89,000  2023   2000p km

In [18]:
df['price']=df['price'].str.replace(',','')

In [19]:
df

    price  year  km_driven
0   45000  2026  45,000 km
1  231100  2024  22,000 km
2   40000  year  21,000 km
3   21000    na  12,000 km
4   15000  2025  23,000 km
5   18000  2021  24,000 km
6     NaN  2022  32,000 km
7   price  2021  21,000 km
8   89000  2023   2000p km

In [20]:
df=df[df['price'].str.isnumeric()]

In [21]:
df

    price  year  km_driven
0   45000  2026  45,000 km
1  231100  2024  22,000 km
2   40000  year  21,000 km
3   21000    na  12,000 km
4   15000  2025  23,000 km
5   18000  2021  24,000 km
8   89000  2023   2000p km

In [22]:
df.shape

(7, 3)

In [23]:
df.info()

<class 'pandas.DataFrame'>
Index: 7 entries, 0 to 8
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   price      7 non-null      str
 1   year       7 non-null      str
 2   km_driven  7 non-null      str
dtypes: str(3)
memory usage: 224.0 bytes

In [24]:
df['km_driven']=df['km_driven'].str.replace(',','')

In [25]:
df

    price  year km_driven
0   45000  2026  45000 km
1  231100  2024  22000 km
2   40000  year  21000 km
3   21000    na  12000 km
4   15000  2025  23000 km
5   18000  2021  24000 km
8   89000  2023  2000p km

In [26]:
df['km_driven'].str.split(" ")

0    [45000, km]
1    [22000, km]
2    [21000, km]
3    [12000, km]
4    [23000, km]
5    [24000, km]
8    [2000p, km]
Name: km_driven, dtype: object

In [28]:
df['km_driven'].str.split(" ").str.get(0)

0    45000
1    22000
2    21000
3    12000
4    23000
5    24000
8    2000p
Name: km_driven, dtype: object

In [29]:
df['km_driven']=df['km_driven'].str.split(" ").str.get(0)

In [30]:
df

    price  year km_driven
0   45000  2026     45000
1  231100  2024     22000
2   40000  year     21000
3   21000    na     12000
4   15000  2025     23000
5   18000  2021     24000
8   89000  2023     2000p

In [31]:
df['km_driven']=df['km_driven'].str.replace('2000p','2000')

In [32]:
df

    price  year km_driven
0   45000  2026     45000
1  231100  2024     22000
2   40000  year     21000
3   21000    na     12000
4   15000  2025     23000
5   18000  2021     24000
8   89000  2023      2000