In [1]:
## make3 a csv file of following data 
## roll no ,name , book_title ,issue date,returndate,fine make the 15 enteies
## 1 no of book issued by each student
## 2 total fine paid by each student
## 3 how mant times student issued the same book 
## 4 calculate the avg ,max,min fine paid by each student
## 5 total fine paid by branch wise
## 6 no of book issued date wise

In [2]:
import pandas as pd 
import numpy as np

In [3]:
data=pd.read_csv('sample3.csv')
df=pd.DataFrame(data)

In [4]:
df

,roll_no,name,book_title,issue_date,return_date,fine
0,22001,Aarav Singh,Computer Networks,12-09-2004,15-05-2026,15
1,22002,Priya Sharma,Data Structures in C,03-05-2026,17-05-2026,16
2,22003,Rohan Verma,Database Management Systems,05-05-2026,19-05-2026,0
3,22004,Ananya Gupta,Computer Networks,07-05-2026,21-05-2026,10
4,22005,Vivek Kumar,Operating System Concepts,09-05-2026,23-05-2026,5
5,22006,Sneha Mishra,Machine Learning Basics,11-05-2026,25-05-2026,89
6,22007,Aditya Yadav,Artificial Intelligence,13-05-2026,27-05-2026,30
7,22008,Neha Patel,Full Stack Web Development,15-05-2026,29-05-2026,20
8,22009,Rahul Tiwari,Java Programming,17-05-2026,31-05-2026,18
9,22010,Kavya Jain,C++ Fundamentals,19-05-2026,02-06-2026,1
10,22011,Arjun Pandey,Linux Administration,21-05-2026,04-06-2026,59
11,22012,Pooja Singh,Cloud Computing Essentials,23-05-2026,06-06-2026,20
12,22013,Mohit Saxena,Cyber Security Handbook,25-05-2026,08-06-2026,40
13,22014,Isha Agarwal,Data Analytics with Python,27-05-2026,10-06-2026,60
14,22015,Nitin Dubey,Software Engineering,29-05-2026,12-06-2026,80

In [5]:
r=df.groupby('name')['fine'].count()

In [6]:
r

name
Aarav Singh     1
Aditya Yadav    1
Ananya Gupta    1
Arjun Pandey    1
Isha Agarwal    1
Kavya Jain      1
Mohit Saxena    1
Neha Patel      1
Nitin Dubey     1
Pooja Singh     1
Priya Sharma    1
Rahul Tiwari    1
Rohan Verma     1
Sneha Mishra    1
Vivek Kumar     1
Name: fine, dtype: int64

In [7]:
r=df.groupby('name')['fine'].sum()

In [8]:
r

name
Aarav Singh     15
Aditya Yadav    30
Ananya Gupta    10
Arjun Pandey    59
Isha Agarwal    60
Kavya Jain       1
Mohit Saxena    40
Neha Patel      20
Nitin Dubey     80
Pooja Singh     20
Priya Sharma    16
Rahul Tiwari    18
Rohan Verma      0
Sneha Mishra    89
Vivek Kumar      5
Name: fine, dtype: int64

In [9]:
df.groupby(['roll_no','name','book_title']).size()

roll_no  name          book_title
22001    Aarav Singh   Computer Networks              1
22002    Priya Sharma  Data Structures in C           1
22003    Rohan Verma   Database Management Systems    1
22004    Ananya Gupta  Computer Networks              1
22005    Vivek Kumar   Operating System Concepts      1
22006    Sneha Mishra  Machine Learning Basics        1
22007    Aditya Yadav  Artificial Intelligence        1
22008    Neha Patel    Full Stack Web Development     1
22009    Rahul Tiwari  Java Programming               1
22010    Kavya Jain    C++ Fundamentals               1
22011    Arjun Pandey  Linux Administration           1
22012    Pooja Singh   Cloud Computing Essentials     1
22013    Mohit Saxena  Cyber Security Handbook        1
22014    Isha Agarwal  Data Analytics with Python     1
22015    Nitin Dubey   Software Engineering           1
dtype: int64

In [10]:
df.groupby(['roll_no','name']).agg({'fine':['mean','max','min']})

                      fine
                      mean max min
roll_no name
22001   Aarav Singh   15.0  15  15
22002   Priya Sharma  16.0  16  16
22003   Rohan Verma    0.0   0   0
22004   Ananya Gupta  10.0  10  10
22005   Vivek Kumar    5.0   5   5
22006   Sneha Mishra  89.0  89  89
22007   Aditya Yadav  30.0  30  30
22008   Neha Patel    20.0  20  20
22009   Rahul Tiwari  18.0  18  18
22010   Kavya Jain     1.0   1   1
22011   Arjun Pandey  59.0  59  59
22012   Pooja Singh   20.0  20  20
22013   Mohit Saxena  40.0  40  40
22014   Isha Agarwal  60.0  60  60
22015   Nitin Dubey   80.0  80  80

In [11]:
df.groupby('issue_date').size()

issue_date
03-05-2026    1
05-05-2026    1
07-05-2026    1
09-05-2026    1
11-05-2026    1
12-09-2004    1
13-05-2026    1
15-05-2026    1
17-05-2026    1
19-05-2026    1
21-05-2026    1
23-05-2026    1
25-05-2026    1
27-05-2026    1
29-05-2026    1
dtype: int64

In [12]:
df['branch']=['cse','ece','cse','cse','cse','cse','ece','cse','cse','cse','cse','ece','cse','cse','cse']

In [13]:
df

,roll_no,name,book_title,issue_date,return_date,fine,branch
0,22001,Aarav Singh,Computer Networks,12-09-2004,15-05-2026,15,cse
1,22002,Priya Sharma,Data Structures in C,03-05-2026,17-05-2026,16,ece
2,22003,Rohan Verma,Database Management Systems,05-05-2026,19-05-2026,0,cse
3,22004,Ananya Gupta,Computer Networks,07-05-2026,21-05-2026,10,cse
4,22005,Vivek Kumar,Operating System Concepts,09-05-2026,23-05-2026,5,cse
5,22006,Sneha Mishra,Machine Learning Basics,11-05-2026,25-05-2026,89,cse
6,22007,Aditya Yadav,Artificial Intelligence,13-05-2026,27-05-2026,30,ece
7,22008,Neha Patel,Full Stack Web Development,15-05-2026,29-05-2026,20,cse
8,22009,Rahul Tiwari,Java Programming,17-05-2026,31-05-2026,18,cse
9,22010,Kavya Jain,C++ Fundamentals,19-05-2026,02-06-2026,1,cse
10,22011,Arjun Pandey,Linux Administration,21-05-2026,04-06-2026,59,cse
11,22012,Pooja Singh,Cloud Computing Essentials,23-05-2026,06-06-2026,20,ece
12,22013,Mohit Saxena,Cyber Security Handbook,25-05-2026,08-06-2026,40,cse
13,22014,Isha Agarwal,Data Analytics with Python,27-05-2026,10-06-2026,60,cse
14,22015,Nitin Dubey,Software Engineering,29-05-2026,12-06-2026,80,cse

In [14]:
df.groupby('branch')['fine'].count()

branch
cse    12
ece     3
Name: fine, dtype: int64

In [15]:
df

,roll_no,name,book_title,issue_date,return_date,fine,branch
0,22001,Aarav Singh,Computer Networks,12-09-2004,15-05-2026,15,cse
1,22002,Priya Sharma,Data Structures in C,03-05-2026,17-05-2026,16,ece
2,22003,Rohan Verma,Database Management Systems,05-05-2026,19-05-2026,0,cse
3,22004,Ananya Gupta,Computer Networks,07-05-2026,21-05-2026,10,cse
4,22005,Vivek Kumar,Operating System Concepts,09-05-2026,23-05-2026,5,cse
5,22006,Sneha Mishra,Machine Learning Basics,11-05-2026,25-05-2026,89,cse
6,22007,Aditya Yadav,Artificial Intelligence,13-05-2026,27-05-2026,30,ece
7,22008,Neha Patel,Full Stack Web Development,15-05-2026,29-05-2026,20,cse
8,22009,Rahul Tiwari,Java Programming,17-05-2026,31-05-2026,18,cse
9,22010,Kavya Jain,C++ Fundamentals,19-05-2026,02-06-2026,1,cse
10,22011,Arjun Pandey,Linux Administration,21-05-2026,04-06-2026,59,cse
11,22012,Pooja Singh,Cloud Computing Essentials,23-05-2026,06-06-2026,20,ece
12,22013,Mohit Saxena,Cyber Security Handbook,25-05-2026,08-06-2026,40,cse
13,22014,Isha Agarwal,Data Analytics with Python,27-05-2026,10-06-2026,60,cse
14,22015,Nitin Dubey,Software Engineering,29-05-2026,12-06-2026,80,cse

In [16]:
df.groupby('branch')['fine'].count()

branch
cse    12
ece     3
Name: fine, dtype: int64

In [17]:
names=['ram','nikhil','navdeep','raja','rohit','sachin','saurab','suraj']

In [18]:
names

['ram', 'nikhil', 'navdeep', 'raja', 'rohit', 'sachin', 'saurab', 'suraj']

In [19]:
df=pd.DataFrame(names,columns=['names'])

In [20]:
df

     names
0      ram
1   nikhil
2  navdeep
3     raja
4    rohit
5   sachin
6   saurab
7    suraj

In [21]:
rs=df['names'].str.upper()

In [22]:
rs

0        RAM
1     NIKHIL
2    NAVDEEP
3       RAJA
4      ROHIT
5     SACHIN
6     SAURAB
7      SURAJ
Name: names, dtype: str

In [23]:
rs=df['names'].str.lower()

In [24]:
rs

0        ram
1     nikhil
2    navdeep
3       raja
4      rohit
5     sachin
6     saurab
7      suraj
Name: names, dtype: str

In [25]:
rs=df['names'].str.strip()

In [26]:
rs

0        ram
1     nikhil
2    navdeep
3       raja
4      rohit
5     sachin
6     saurab
7      suraj
Name: names, dtype: str

In [27]:
rs=df['names'].str.split()

In [28]:
rs

0        [ram]
1     [nikhil]
2    [navdeep]
3       [raja]
4      [rohit]
5     [sachin]
6     [saurab]
7      [suraj]
Name: names, dtype: object

In [30]:
r

name
Aarav Singh     15
Aditya Yadav    30
Ananya Gupta    10
Arjun Pandey    59
Isha Agarwal    60
Kavya Jain       1
Mohit Saxena    40
Neha Patel      20
Nitin Dubey     80
Pooja Singh     20
Priya Sharma    16
Rahul Tiwari    18
Rohan Verma      0
Sneha Mishra    89
Vivek Kumar      5
Name: fine, dtype: int64

In [31]:
rs=df['names'].str.get_dummies()

In [32]:
rs

   navdeep  nikhil  raja  ram  rohit  sachin  saurab  suraj
0        0       0     0    1      0       0       0      0
1        0       1     0    0      0       0       0      0
2        1       0     0    0      0       0       0      0
3        0       0     1    0      0       0       0      0
4        0       0     0    0      1       0       0      0
5        0       0     0    0      0       1       0      0
6        0       0     0    0      0       0       1      0
7        0       0     0    0      0       0       0      1

In [33]:
rs=df['names'].str.startswith('E')

In [34]:
rs

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: names, dtype: bool

In [35]:
rs=df['names'].str.count('a')

In [36]:
rs

0    1
1    0
2    1
3    2
4    0
5    1
6    2
7    1
Name: names, dtype: int64